name: Build and start app; run Cypress E2E tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build app
        uses: actions/checkout@v2
        with:
          build: yarn install && yarn build:web && cd packages/web

      - name: Start app and run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          start: yarn start & wait-on http://localhost:3001
          wait-on: 'http://localhost:3001'
          wait-on-timeout: 60
          spec: cypress/e2e/home_page.cy.js