name: Build and start app; run Cypress E2E tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and start app, run Cypress E2E tests
        uses: cypress-io/github-action@v4
        with:
          build: yarn build-cypress
          start: yarn cypress